name: benchmark

on: push

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Benchmarking Python scripts
        run: |
          for py_script in Python/*.py; do
          time --format "%C \t %E" python $py_script;
          done
