name: benchmark

on: push

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Benchmarking Python programs
        run: |
          for py_script in Python/*.py; do
          echo ~~~~~~~~~~~~~~~~~~;
          echo $py_script;
          chmod +x $py_script;
          time ./$py_script;
          echo ~~~~~~~~~~~~~~~~~~;
          echo ;
          done
