name: Lint

on: [push, pull_request]

jobs:
  run-linter:
    name: Run Black linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Black linter
        run: pip install black
      - name: Run linter
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          black: true
          auto_fix: true
          commit_message: 'Fix code style issues with Black'
          git_name: 'Black_Linter'
